export const APP_LOAD = 'APP_LOAD';
export const API_REQUEST = 'API_REQUEST';
export const API_RESPONSE_RECEIVED = 'API_RESPONSE_RECEIVED';

export const STREAM_URL_REQUEST = "STREAM_URL_REQUEST";
export const STREAM_URL_RESPONSE = "STREAM_URL_RESPONSE";
export const STREAM_URL_ERROR = 'STREAM_URL_ERROR';

export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST';
export const VIDEO_LIST_RESPONSE = 'VIDEO_LIST_RESPONSE';
export const VIDEO_LIST_ERROR = 'VIDEO_LIST_ERROR';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR';

export default { APP_LOAD };
